apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: codegen-210325
  janus-idp.io/tekton: codegen-210325
  backstage.io/kubernetes-id: codegen-210325
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: codegen-210325
resources:
  - application-dev.yaml